# Generated by Django 4.1.5 on 2023-02-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2004-12-8'),
            preserve_default=False,
        ),
    ]
